# Generated by Django 5.0.7 on 2024-08-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="해시태그명"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hashtag",
                "verbose_name_plural": "Hashtags",
                "db_table": "hashtag",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("instagram", "INSTAGRAM"),
                            ("facebook", "FACEBOOK"),
                            ("twitter", "TWITTER"),
                            ("threads", "THREADS"),
                        ],
                        max_length=125,
                        verbose_name="출처 사이트",
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        max_length=255, verbose_name="사이트 내에서의 id(pk)"
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="게시글 내용")),
                (
                    "view_cnt",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "like_cnt",
                    models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "share_cnt",
                    models.PositiveIntegerField(default=0, verbose_name="공유 횟수"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="사용자_id",
                    ),
                ),
                (
                    "hashtag",
                    models.ManyToManyField(
                        to="article.hashtag", verbose_name="해시태그_id"
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "article",
            },
        ),
    ]
