# Generated by Django 5.0.7 on 2024-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.TextField(
                default="", max_length=125, verbose_name="게시글 제목"
            ),
            preserve_default=False,
        ),
    ]
