# Generated by Django 5.0.7 on 2024-08-24 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("article", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자_id",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="hashtag",
            field=models.ManyToManyField(
                to="article.hashtag", verbose_name="해시태그_id"
            ),
        ),
    ]
